version: "3.3"
services:

  linchpino-core:
    image: ghcr.io/linchpino/linchpino-core:$CurrentBranch
    container_name: linchpino-core
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    command: "mvn spring-boot:run -Dspring-boot.run.jvmArguments='\
       -DAPPLICATION_URL=$APPLICATION_URL \
       -DPOSTGRES_USERNAME=$POSTGRES_USERNAME \
       -DPOSTGRES_PASSWORD=$POSTGRES_PASSWORD \
       -DPOSTGRES_URL=$POSTGRES_URL \
       -DMAIL_PASSWORD=$MAIL_PASSWORD \
       -DGEMINI_API_KEY=$GEMINI_API_KEY \
       -DOPEN_AI_API_KEY=$OPEN_AI_API_KEY'"
    env_file:
      - ./.env
    volumes:
      - ./.env:/app/.env
      - ./certkeys:/app/certkeys
      - ./ardent-window.json:/app/ardent-window.json
  postgres:
    image: postgres:16
    container_name: linchpino-db
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
    #only used for dev branches
      #- ./PostgresData:/var/lib/postgresql/data
      - ./initscripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USERNAME
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST_AUTH_METHOD=trust

  pgadmin:
    image: dpage/pgadmin4
    container_name: linchpino-pgadmin4
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    volumes:
       - ./PgadminData:/var/lib/pgadmin

