version: "3.3"
services:

  linchpino-core:
    image: ghcr.io/linchpino/linchpino-core:development
    container_name: linchpino-core
    restart: unless-stopped
    ports:
      - "8082:8080"
    command: "mvn spring-boot:run -Dspring-boot.run.jvmArguments='-DPOSTGRES_USERNAME=linchpinodbuser -DPOSTGRES_PASSWORD=Ps@135792468 -DPOSTGRES_URL=jdbc:postgresql://api-dev.linchpino.com:5432/linchpinocore'"

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./PostgresData:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}
      - POSTGRES_USER=${{secrets.POSTGRES_USER}
      - POSTGRES_DB=${{secrets.POSTGRES_DB}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${{secrets.PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${{secrets.PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./PgadminData:/var/lib/pgadmin

