version: "3.3"
services:

  linchpino-core:
    image: ghcr.io/linchpino/linchpino-core:$CurrentBranch
    container_name: linchpino-core
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    command: "mvn spring-boot:run -Dspring-boot.run.jvmArguments='\
       -DPOSTGRES_USERNAME=$POSTGRES_USERNAME \ 
       -DPOSTGRES_PASSWORD=$POSTGRES_PASSWORD \
       -DPOSTGRES_URL=$POSTGRES_URL'"

  postgres:
    image: postgres
    container_name: linchpino-db
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./PostgresData:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USERNAME
      - POSTGRES_DB=$POSTGRES_DB

  pgadmin:
    image: dpage/pgadmin4
    container_name: linchpino-pgadmin4
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    volumes:
      - ./PgadminData:/var/lib/pgadmin

