version: "3.3"
services:

  linchpino-core:
    image: ghcr.io/linchpino/linchpino-core:development
    container_name: linchpino-core
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8082:8080"
    command: "mvn spring-boot:run -Dspring-boot.run.jvmArguments='\
       -DPOSTGRES_USERNAME=${{secrets.POSTGRES_USERNAME}} \ 
       -DPOSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}} \
       -DPOSTGRES_URL=${{secrets.DPOSTGRES_URL}}'"

  postgres:
    image: postgres
    container_name: linchpino-db
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./PostgresData:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}
      - POSTGRES_USER=${{secrets.POSTGRES_USERNAME}}
      - POSTGRES_DB=${{secrets.POSTGRES_DB}}

  pgadmin:
    image: dpage/pgadmin4
    container_name: linchpino-pgadmin4
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${{secrets.PGADMIN_DEFAULT_EMAIL}}
      PGADMIN_DEFAULT_PASSWORD: ${{secrets.PGADMIN_DEFAULT_PASSWORD}}
    volumes:
      - ./PgadminData:/var/lib/pgadmin

