spring:
  application:
    name: linchpino-service

  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY:api-key}

  datasource:
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/linchpino}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: ${HIBERNATE_SHOW_SQL:true}
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
  mail:
    host: ${MAIL_SERVER_URL:smtp.gmail.com}
    port: 587
    username: ${MAIL_USERNAME:linchpino@linchpino.com}
    password: ${MAIL_PASSWORD:Password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          from: no-reply@linchpino.com
mail.from.name: Linchpino

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
rsa:
  private-key: ${PRIVATE_KEY:classpath:certs/private.pem}
  public-key: ${PUBLIC_KEY:classpath:certs/public.pem}

logging:
  level:
    org:
      springframework:
        security: trace

linkedin:
  clientId: ${LINKEDIN_CLIENT_ID:fake_client_id}
  secret: ${LINKEDIN_CLIENT_SECRET:fake_client_secret}

password:
  policyRegex: "^[A-Za-z\\d@$!%*?&]{6,}$"

application:
  url:  ${APPLICATION_URL:https://linchpino.liara.run}

meet:
  credential: ${MEET_CREDENTIAL:file:/path/to/file}


