spring:
    application:
        name: linchpino-service

    datasource:
        driverClassName: org.postgresql.Driver
        username: ${POSTGRES_USERNAME:linchpinodbuser}
        password: ${POSTGRES_PASSWORD:Ps@135792468}
        url: ${POSTGRES_URL:jdbc:postgresql://api-dev.linchpino.com:5432/linchpinocore}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
        show-sql: ${HIBERNATE_SHOW_SQL:true}
        properties:
            hibernate:
                format_sql: true
