spring:
  application:
    name: linchpino-service

  datasource:
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/linchpino}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: ${HIBERNATE_SHOW_SQL:true}
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,metrics
      cors:
        allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
rsa:
  private-key: ${PRIVATE_KEY:classpath:certs/private.pem}
  public-key: ${PUBLIC_KEY:classpath:certs/public.pem}

logging:
  level:
    org:
      springframework:
        security: trace
