package com.linchpino.ai.service.model;

import java.util.List;

public class ResumeMockData {
    protected List<String> getResumeLines() {
        return List.of("Contact",
            "en.masoomi@gmail.com",
            "www.linkedin.com/in/",
            "mohammadmh (LinkedIn)",
            "gitlab.com/en.masoomi (Personal)",
            "github.com/mohammadmasoomi2",
            "(Personal)",
            "Top Skills",
            "Linux",
            "Java",
            "Spring Framework",
            "Certifications",
            "MySQL Essential Training",
            "Java SE 8 Programmer",
            "Java Memory Management:",
            "Garbage Collection, JVM Tuning,",
            "and Spotting Memory Leaks",
            "MongoDB Essential Training",
            "Publications",
            "دانش آموزان و شبکه های اجتماعی؛",
            "نقش والدین در چگونگی شکل",
            "گیری هویت مجازی دانش آموزان",
            "Mohammad Masoomi",
            "Homayoun",
            "Software Developer",
            "Eindhoven, North Brabant, Netherlands",
            "Summary",
            "I am a java developer. Besides, I am an easy-going person and have",
            "a sense of humor. Most of the time, I prefer to be at peace with the",
            "world. The others say I am on time for appointments and deadlines.",
            "Exploring the world and learning new things makes me feel excited",
            "and lively.",
            "Experience",
            "APS Group",
            "Software Engineer",
            "August 2023 - Present (1 year 1 month)",
            "Netherlands",
            "Zitel ",
            "Java Software Developer",
            "August 2022 - August 2023 (1 year 1 month)",
            "Tehran, Tehran, Iran",
            "Sadad Informatics Corporation",
            "1 year 1 month",
            "Development Team Lead",
            "March 2022 - August 2022 (6 months)",
            "Tehran, Iran",
            "Java Developer",
            "August 2021 - March 2022 (8 months)",
            "Tehran, Iran",
            "Teanab parto shargh",
            "Java Developer",
            "September 2018 - August 2021 (3 years)",
            "Tehran Province, Iran",
            "  Page 1 of 2",
            "   ",
            "Tarahan Novin",
            "Software Developer",
            "August 2014 - June 2018 (3 years 11 months)",
            "Tehran, Iran",
            "I used to develop windows applications by C#. Besides, I have developed a",
            "Nodejs application and web applications with ExpresJs Before I focus on Java",
            "professionally.",
            "Education",
            "Amirkabir University of Technology - Tehran Polytechnic");
    }
}
