CREATE TABLE jobseeker_feedback
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by          BIGINT,
    created_on          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    modified_by         BIGINT,
    modified_on         TIMESTAMP WITHOUT TIME ZONE,
    jobseeker_id        BIGINT                                  NOT NULL,
    interview_id        BIGINT                                  NOT NULL,
    satisfaction_status INTEGER                                 NOT NULL,
    content             TEXT,
    CONSTRAINT pk_jobseeker_feedback PRIMARY KEY (id),
    CONSTRAINT fk_jobseeker
        FOREIGN KEY (jobseeker_id)
            REFERENCES account (id),
    CONSTRAINT fk_interview
        FOREIGN KEY (interview_id)
            REFERENCES interview (id),
    CONSTRAINT uq_jobseeker_interview UNIQUE (jobseeker_id, interview_id)
);
