create table interview_log
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by BIGINT                      NOT NULL references account (id),
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    type       SMALLINT                    NOT NULL
);
