CREATE TABLE schedule
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    duration        INTEGER                                 NOT NULL,
    account_id      BIGINT                                  NOT NULL,
    recurrence_type VARCHAR(255)                            NOT NULL,
    interval        INTEGER                                 NOT NULL,
    end_time        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_schedule PRIMARY KEY (id)
);

ALTER TABLE schedule
    ADD CONSTRAINT uc_schedule_account UNIQUE (account_id);

ALTER TABLE schedule
    ADD CONSTRAINT FK_SCHEDULE_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account (id);

CREATE TABLE weekly_recurrence_days
(
    schedule_id BIGINT       NOT NULL,
    day_of_week VARCHAR(255) NOT NULL
);

ALTER TABLE weekly_recurrence_days
    ADD CONSTRAINT fk_weekly_recurrence_days_on_schedule FOREIGN KEY (schedule_id) REFERENCES schedule (id);

CREATE TABLE monthly_recurrence_days
(
    schedule_id  BIGINT  NOT NULL,
    day_of_month INTEGER NOT NULL
);

ALTER TABLE monthly_recurrence_days
    ADD CONSTRAINT fk_monthly_recurrence_days_on_schedule FOREIGN KEY (schedule_id) REFERENCES schedule (id);
