CREATE TABLE resume
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_resume PRIMARY KEY (id)
);

CREATE TABLE resume_lines
(
    line      VARCHAR(1000) NOT NULL,
    resume_id BIGINT        NOT NULL
);

ALTER TABLE resume_lines
    ADD CONSTRAINT fk_resume_lines_on_resume FOREIGN KEY (resume_id) REFERENCES resume (id);
