CREATE TABLE account
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by  CHAR(255),
    created_on  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    modified_by CHAR(255),
    modified_on TIMESTAMP WITHOUT TIME ZONE,
    first_name  VARCHAR(255),
    last_name   VARCHAR(255),
    email       VARCHAR(255),
    password    VARCHAR(255),
    type        VARCHAR(255),
    status      VARCHAR(255),
    CONSTRAINT pk_account PRIMARY KEY (id)
);

CREATE TABLE interview_type
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by  CHAR(255),
    created_on  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    modified_by CHAR(255),
    modified_on TIMESTAMP WITHOUT TIME ZONE,
    name        VARCHAR(255),
    CONSTRAINT pk_interview_type PRIMARY KEY (id)
);

CREATE TABLE job_position
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by  CHAR(255),
    created_on  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    modified_by CHAR(255),
    modified_on TIMESTAMP WITHOUT TIME ZONE,
    title       VARCHAR(255),
    CONSTRAINT pk_job_position PRIMARY KEY (id)
);


CREATE TABLE mentor_time_slot
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by  CHAR(255),
    created_on  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    modified_by CHAR(255),
    modified_on TIMESTAMP WITHOUT TIME ZONE,
    account_id  BIGINT                                  NOT NULL,
    date        date,
    from_time   TIMESTAMP WITHOUT TIME ZONE,
    to_tome     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_mentor_time_slot PRIMARY KEY (id)
);

ALTER TABLE mentor_time_slot
    ADD CONSTRAINT FK_MENTOR_TIME_SLOT_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account (id);



CREATE TABLE interview
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by            CHAR(255),
    created_on            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    modified_by           CHAR(255),
    modified_on           TIMESTAMP WITHOUT TIME ZONE,
    job_position_id       BIGINT                                  NOT NULL,
    interview_type_id     BIGINT                                  NOT NULL,
    time_slot_id          BIGINT                                  NOT NULL,
    mentor_account_id     BIGINT                                  NOT NULL,
    job_seeker_account_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_interview PRIMARY KEY (id)
);

ALTER TABLE interview
    ADD CONSTRAINT FK_INTERVIEW_ON_INTERVIEW_TYPE FOREIGN KEY (interview_type_id) REFERENCES interview_type (id);

ALTER TABLE interview
    ADD CONSTRAINT FK_INTERVIEW_ON_JOB_POSITION FOREIGN KEY (job_position_id) REFERENCES job_position (id);

ALTER TABLE interview
    ADD CONSTRAINT FK_INTERVIEW_ON_JOB_SEEKER_ACCOUNT FOREIGN KEY (job_seeker_account_id) REFERENCES account (id);

ALTER TABLE interview
    ADD CONSTRAINT FK_INTERVIEW_ON_MENTOR_ACCOUNT FOREIGN KEY (mentor_account_id) REFERENCES account (id);

ALTER TABLE interview
    ADD CONSTRAINT FK_INTERVIEW_ON_TIME_SLOT FOREIGN KEY (time_slot_id) REFERENCES mentor_time_slot (id);

CREATE TABLE mentor_interview_type
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by        CHAR(255),
    created_on        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    modified_by       CHAR(255),
    modified_on       TIMESTAMP WITHOUT TIME ZONE,
    interview_type_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_mentor_interview_type PRIMARY KEY (id)
);

ALTER TABLE mentor_interview_type
    ADD CONSTRAINT FK_MENTOR_INTERVIEW_TYPE_ON_INTERVIEW_TYPE FOREIGN KEY (interview_type_id) REFERENCES interview_type (id);
