CREATE TABLE payment
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by   BIGINT,
    created_on   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    modified_by  BIGINT,
    modified_on  TIMESTAMP WITHOUT TIME ZONE,
    status       VARCHAR(255),
    ref_number   VARCHAR(255)                            NOT NULL,
    amount       DECIMAL,
    interview_id BIGINT,
    CONSTRAINT pk_payment PRIMARY KEY (id)
);

ALTER TABLE payment
    ADD CONSTRAINT uc_payment_refnumber UNIQUE (ref_number);

ALTER TABLE payment
    ADD CONSTRAINT FK_PAYMENT_ON_INTERVIEW FOREIGN KEY (interview_id) REFERENCES interview (id);
