create TABLE role (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by  BIGINT,
    created_on  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    modified_by BIGINT,
    modified_on TIMESTAMP WITHOUT TIME ZONE,
    role        INTEGER,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

create TABLE account_role (
    account_id BIGINT NOT NULL,
    role_id    BIGINT NOT NULL,
    CONSTRAINT pk_account_role PRIMARY KEY (account_id, role_id)
);

alter table account_role
    add CONSTRAINT fk_accrol_on_account FOREIGN KEY (account_id) REFERENCES account (id);

alter table account_role
    add CONSTRAINT fk_accrol_on_role FOREIGN KEY (role_id) REFERENCES role (id);
