name: Build and Deploy development branch to linchpino-core-dev server
on:
  push:
    branches:
      - '**'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  Deploy-to-linchpino-core-server:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write 
    steps:
      - name: Connect to linchpino-core on GCP instance
        run: |
          cd ${{ secrets.WORK_DIR }}
          sudo git fetch --all && sudo git checkout ${GITHUB_REF##*/}	&& sudo git checkout docker-compose.yml init.sql
          sudo sed -i "s/POSTGRES_DB=.*/POSTGRES_DB=${GITHUB_REF##*\/}/" /opt/actions-runner/.env
          sudo sed -i "s/POSTGRES_URL=.*/POSTGRES_URL=jdbc:postgresql:\/\/api-dev.linchpino.com:5432\/${GITHUB_REF##*\/}/" /opt/actions-runner/.env
          sudo sed -i "s/\$currentbranches/${GITHUB_REF##*\/}/g" init.sql
          sudo sed -i "s/\/linchpino-core:.*/\/linchpino-core:${GITHUB_REF##*\/}/" docker-compose.yml
          docker-compose down && docker-compose up -d
