name: Build and Deploy Current Branch to linchpino-core-dev server

on:
  pull_request:
      branches: [development]
      types: [opened,reopened]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Deploy-to-linchpino-core-server:
      runs-on: self-hosted
      permissions:
        contents: read
        packages: write
      steps:
        - name: Connect to linchpino-core on GCP instance
          env:
            PR_NUMBER: ${{ github.event.number }}
            ALLMYSECRETS: ${{ toJson(secrets) }}
            ALLMYVARS: ${{ toJSON(vars) }}
          run: |
            echo $ALLMYSECRETS > /opt/.linchpino-core-secrets 
            echo $ALLMYVARS > /opt/.linchpino-core-vars
            sudo sed -i "s/[{|}]//g" /opt/.linchpino-core-secrets && sudo sed -i "s/\": /=/g" /opt/.linchpino-core-secrets && sudo sed -i "s/[\"]//g" /opt/.linchpino-core-secrets && sudo sed -i "s/,/\\n/g" /opt/.linchpino-core-secrets && sudo sed -i "s/^ //g" /opt/.linchpino-core-secrets 
            sudo  sed -i "s/[{|}]//g" /opt/.linchpino-core-vars && sudo sed -i "s/\": /=/g" /opt/.linchpino-core-vars && sudo sed -i "s/[\"]//g" /opt/.linchpino-core-vars && sudo sed -i "s/,/\\n/g" /opt/.linchpino-core-vars && sudo sed -i "s/^ //g" /opt/.linchpino-core-vars 
            sudo echo "LANG=C.UTF-8" > /opt/actions-runner/.env && cat /opt/.linchpino-core-secrets /opt/.linchpino-core-vars >> /opt/actions-runner/.env
            cd ${{ secrets.WORK_DIR }}
            cat /opt/actions-runner/.env > .env
            sudo git fetch --all
            sudo git reset --hard
            echo "GITHUB_REF : "${GITHUB_REF##*/}
            echo "GITHUB_REF : "${GITHUB_REF}
            echo "GITHUB_HEAD_REF :" ${GITHUB_HEAD_REF}
            if [ ${GITHUB_REF##*/} == "merge" ]; then
            currentBranch=pr-$PR_NUMBER
            sudo git checkout origin/development --  docker-compose.yml
            echo "the current branch is : " $currentBranch
            else
            currentBranch=${GITHUB_REF##*/}
            echo "the current branch is : " $currentBranch
            sudo git checkout origin/$currentBranch
            sudo git checkout origin/$currentBranch --  docker-compose.yml
            sudo git checkout origin/$currentBranch -- ./initscripts/init.sql
            fi
            sudo sed -i "s/POSTGRES_DB=.*/POSTGRES_DB=$currentBranch/" /opt/actions-runner/.env
            export POSTGRES_DB=$currentBranch
            sudo sed -i "s/POSTGRES_URL=.*/POSTGRES_URL=jdbc:postgresql:\/\/api-dev.linchpino.com:5432\/$currentBranch/" /opt/actions-runner/.env
            export POSTGRES_URL=jdbc:postgresql://api-dev.linchpino.com:5432/$currentBranch
            sudo sed -i "s/\$currentbranches/$currentBranch/g" ./initscripts/init.sql
            sudo sed -i "s/\/linchpino-core:.*/\/linchpino-core:$currentBranch/" docker-compose.yml
            if [ ${GITHUB_REF##*/} == "development" ]; then
            sudo sed -i "s/#-/"-"/" docker-compose.yml
            fi
            docker-compose stop && docker-compose rm -f linchpino-core && docker-compose pull linchpino-core
            docker-compose up -d
