name: Run SonarQube with Maven

on: 
    push:
     branches:
      - development
    pull_request:
      types: [opened, synchronize, reopened] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven cloud
      run:  mvn -B verify sonar:sonar -Dsonar.projectKey=linchpino-core -Dsonar.organization=linchpino -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN
      env:
        GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
        SONARCLOUD_TOKEN: ${{ secrets.SONAR_TOKEN }}
